### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by white-ws** [white-ws/viet-salary#2]
- [ ] Vietnamese language
- [ ] Salary range for each field
- [ ] Salary range for each company
- [ ] Company page
- [ ] Upload verification document 
- [ ] Admin/approval page
- [ ] autofill form
